### ISSUE TITLE
Will not compile on a modern Linux system - BOUNTY $$$

### ISSUE THREAD

**Issue by JonathanWilbur** [JonathanWilbur/isode-8.0#1]
## Description

This repository will not compile and install on a modern Linux system. This bug bounty is for a C developer that can get this to compile and install via the `everything` and `inst-everything` make targets on the latest `ubuntu` Docker container with no change to functionality of the compiled outputs. I think this is something a competent C developer could knock out within an 8-hour day.

## Background

This repo contains several projects, such as an X.500 directory server, a CMIP server, an FTAM server, and a few other applications that run in an OSI networking environment. OSI networking was defeated by TCP/IP in the popularity contest, so this repository has fallen into disrepair, but the original authors of it put a lot of effort into creating a lot of complex and innovative software that I believe is worth preserving. I have also written [my own X.500 directory server](https://github.com/Wildboar-Software/directory) ([docs](https://wildboar-software.github.io/directory/)), which I would like to integrate with the X.500 directory server in this repository for integration testing purposes. By working on this, you'd help to preserve a fascinating little ecosystem of what an alternative Internet could have looked like.

## Permitted

- Changing source code
- Changes to build files or the file layout
- Installing extra dependencies

## Not Permitted

- Changing functionality
- Requiring old versions of GCC, Make, Bison, Flex, Git, Ubuntu, etc. Dependencies must be up-to-date.

If you feel that an exception needs to be made for the above, please discuss it on this issue page.

## The Compiling Issue

Some of the compilation issues have been addressed here: https://github.com/Kampbell/isode-8.0/issues/7

## Starting the DSA

I have not been able to confirm this works, because, obviously, I could not even build this project, but I believe section 14.2 / page 129 of [this documentation](https://github.com/JonathanWilbur/isode-8.0/blob/develop/docs/volume5.pdf) will tell you how to start the DSA (that's another name for a _server_, in this case).

If you get the whole project building and installing, but it does not start up successfully, also discuss this on this issue page. I would actually be willing to help get it started; it's just the compiling that has me stumped.

## Getting Started

Start an `ubuntu` Docker container by running `docker run -it ubuntu:latest /bin/bash`. (Technically, you could probably get away with working on an Ubuntu virtual machine or bare-metal machine, if you wish, but in the end, this project MUST compile, install, and run within the latest `ubuntu` Docker image.)

Run these commands in order, with the exact casing you see below: 

```
apt update
apt install -y build-essential git bison flex
git clone https://github.com/Kampbell/isode-8.0.git
cd isode-8.0
cp config/linux.h h/config.h
cp config/linux.make config/CONFIG.make
cp config/*.local support/
./make everything
./make inst-everything
```

Currently, you will not be able to make it past the `./make everything` command. This is where your critical thinking begins! Do what you need to do to get this to build within the Docker container.

## Submission

You do not need to have the whole compilation and installation automated. If you can simply submit code changes and a list of steps (possibly manual) that need to be done / automated to get this repo to build, install, and run per the requirements above, that will be sufficient to claim the bounty. You do not need to Dockerize this to claim the bounty.

**Comment by abcpro1** [comment]
Hello, I would like to inform you that I will be working on renovating this C software.
Thanks.

**Comment by malachib** [comment]
Would transitioning everything to CMake be acceptable?

**Comment by JonathanWilbur** [comment]
@malachib sure! Just make sure that the targets still build all components.

**Comment by abcpro1** [comment]
~Is it acceptable if the server compiles and executes correctly in x86 32 bits mode?~. never mind I got it working.

**Comment by abcpro1** [comment]
I have finished. How do I close this issue? Do I submit a pull request? I have every target compiling (I mean absolutely every target, I haven't disabled any in the Makefiles). I have written Linux specific code where appropriate. The directory server is working, the client program connects and functions as excepted, and everything is dockerized. What should I do now?

**Comment by JonathanWilbur** [comment]
> I have finished. How do I close this issue? Do I submit a pull request? I have every target compiling (I mean absolutely every target, I haven't disabled any in the Makefiles). I have written Linux specific code where appropriate. The directory server is working, the client program connects and functions as excepted, and everything is dockerized. What should I do now?

Hey, that's great news! I'd prefer a pull request. It is very late at night for me, so I'll look at it in the morning and close the bounty and pay you if it looks good. Thank you!

**Comment by abcpro1** [comment]
I have opened a pull request at #3 .

**Comment by bl00mber** [comment]
@JonathanWilbur I also finished and will send PR today
my version is based on head commit of Kampbell/isode-8.0

**Comment by bl00mber** [comment]
There is a PR #4

**Comment by JonathanWilbur** [comment]
@abcpro1 has solved this.
